### PR TITLE
Improving working on Windows

### PR DESCRIPTION
**Pull request by AzazKamaz**

### CODE REVIEW

**Comment by reapazor** [comment]
Can anyone on Windows confirm this as a fix? 

Does hot reload work for you as well? -- Cause the plugin is going through cert process right now on the UE marketplace and this would be a nice addition to flag.

**Comment by AzazKamaz** [comment]
For me, hot reload works as well

**Comment by shadd-anderson** [comment]
fwiw, I followed all the things @AzazKamaz put in his updated README, and all the errors I had have gone away. Seemed to compile a bit faster too. Haven't tried hot reload yet, though

**Comment by reapazor** [comment]
Lemme know asap! :D i'll merge tonight!

**Comment by shadd-anderson** [comment]
Hot reload works :) Looks like the key is really just that compiler.

**Pull request merged**
