### PR TITLE
Adding extra parentheses to prevent error: '&&' within '||'

### PR DESCRIPTION
**Pull request by ghost**
Got this error on linux and macOS. It's cosmetic, functional nothing changes but the compile option -Wlogical-op-parentheses errors on it

### CODE REVIEW

**Comment by RicardoEPRodrigues** [comment]
I suffered from this issue. When I have the time I'll give it a go! Thank you!

**Comment by reapazor** [comment]
Weird never had this, but it shouldnt  break anything so in it goes.

**Review by reapazor — APPROVED** [review]
Extra safe!

**Comment by RicardoEPRodrigues** [comment]
I think it has to with different version of the compilers... UE4 is very unstable from version to version. On Linux it still has a lot of problems... http://steamcommunity.com/app/396750/discussions/0/333656722966793785/?ctp=4#c133260909494485482

**Pull request merged**
