### PR TITLE
Changed header input order, otherwise code wouldn't compile. (UnrealEngine 4.15.0)

### PR DESCRIPTION
**Pull request by fernandozhu**

### CODE REVIEW

**Comment by reapazor** [comment]
So I find this VERY strange, particularly since I compile it without issue.  Has anyone else seen this? 
What version of UE 4.15?

**Comment by fernandozhu** [comment]
@reapazor UE 4.15.0 on Ubuntu 16.10

**Comment by reapazor** [comment]
Anyone else seeing a need for this ? this a one off?

**Comment by RicardoEPRodrigues** [comment]
I don't think I ever had this issue, but @fernandozhu could you give more information on how to reproduce the issue?

**Comment by twinflyer** [comment]
I had the exact same issue and just came here to report this bug.
We had this on two different machines, both running Ubuntu (one 14.04, other one 16.10). Source built Engine (4.15.1) compiled with clang 3.8 (clang also compiles the plugins).

**Review by reapazor — APPROVED** [review]

**Review by reapazor — COMMENTED** [review]
ERROR: All source files in module "CLionSourceCodeAccess" must include the same precompiled header first.  Currently "/Users/reapazor/Workspaces/dotBunny/Dethol/Game/Project/Plugins/CLionSourceCodeAccess/Source/CLionSourceCodeAccess/Private/CLionSettings.h" is included by most of the source files.  The following source files are not including "/Users/reapazor/Workspaces/dotBunny/Dethol/Game/Project/Plugins/CLionSourceCodeAccess/Source/CLionSourceCodeAccess/Private/CLionSettings.h" as their first include:

**Comment by RicardoEPRodrigues** [comment]
I also get that error.

**Comment by reapazor** [comment]
Ya reverting ;/ that was a bad move :D

**Comment by RicardoEPRodrigues** [comment]
The latest version is giving me this error again. I think UE4 suffers from a bit of instability, because it seems like it wants the most used header file to come first.

**Pull request merged**
