### PR TITLE
Improving CMake generation:

### PR DESCRIPTION
**Pull request by anastasiak2512**
Adding C++11 flag.
Filtering Plugin and Config files out from Sources.
Adding custom targets for build and clean (Mac).

### CODE REVIEW

**Comment by reapazor** [comment]
Does filtering the plugin out of the sources cause any grief when it comes to being able to edit it within CLion?

I found i didn't get code complete (prior) without it being in the sources list (mainly because i wouldn't get the UE side of things).

Otherwise looks good, will just wait on your feedback there and merge her in ... looks great!

**Comment by anastasiak2512** [comment]
If you wanna edit the plugin, then it's better to have plugin sources in, so that CLion can handle these files as a part of a project. But don't think that's what most of the users need. So decided to filter it out. But listening to the feedback will be great.

**Comment by reapazor** [comment]
I'll make an option to toggle on including them, will merge this and just make a todo for that

**Comment by anastasiak2512** [comment]
Thanks.

**Pull request merged**
